log_level: debug
identity_libp2p_dir: /tmp/libp2p
identity_optp2p_dir: /tmp/optp2p
agent_lib_p2p_port: 33212
agent_opt_p2p_port: 43213
telemetry_enable: true
telemetry_port: 48123
gateway_cluster_id: optimum_hoodi_v0_1
gateway_id: local-dockerized
proxy_host:
  - proxy_1:50051
  - proxy_1:50051
eth_topics_subscribe: # 82556a32 is the fork digest for hoodi
  - /eth2/82556a32/beacon_aggregate_and_proof/ssz_snappy
  - /eth2/82556a32/beacon_block/ssz_snappy
  - /eth2/82556a32/voluntary_exit/ssz_snappy
  - /eth2/82556a32/proposer_slashing/ssz_snappy
  - /eth2/82556a32/attester_slashing/ssz_snappy
  - /eth2/82556a32/sync_committee_contribution_and_proof/ssz_snappy
  - /eth2/82556a32/bls_to_execution_change/ssz_snappy
  - /eth2/82556a32/attestation_subnet_0/ssz_snappy
  - /eth2/82556a32/attestation_subnet_1/ssz_snappy
  - /eth2/82556a32/attestation_subnet_2/ssz_snappy
  - /eth2/82556a32/attestation_subnet_3/ssz_snappy
  - /eth2/82556a32/attestation_subnet_4/ssz_snappy
  - /eth2/82556a32/attestation_subnet_5/ssz_snappy
  - /eth2/82556a32/attestation_subnet_6/ssz_snappy
  - /eth2/82556a32/attestation_subnet_7/ssz_snappy
  - /eth2/82556a32/attestation_subnet_8/ssz_snappy
  - /eth2/82556a32/attestation_subnet_9/ssz_snappy
  - /eth2/82556a32/attestation_subnet_10/ssz_snappy
  - /eth2/82556a32/attestation_subnet_11/ssz_snappy
  - /eth2/82556a32/attestation_subnet_12/ssz_snappy
  - /eth2/82556a32/attestation_subnet_13/ssz_snappy
  - /eth2/82556a32/attestation_subnet_14/ssz_snappy
  - /eth2/82556a32/attestation_subnet_15/ssz_snappy
  - /eth2/82556a32/attestation_subnet_16/ssz_snappy
  - /eth2/82556a32/attestation_subnet_17/ssz_snappy
  - /eth2/82556a32/attestation_subnet_18/ssz_snappy
  - /eth2/82556a32/attestation_subnet_19/ssz_snappy
  - /eth2/82556a32/attestation_subnet_20/ssz_snappy
  - /eth2/82556a32/attestation_subnet_21/ssz_snappy
  - /eth2/82556a32/attestation_subnet_22/ssz_snappy
  - /eth2/82556a32/attestation_subnet_23/ssz_snappy
  - /eth2/82556a32/attestation_subnet_24/ssz_snappy
  - /eth2/82556a32/attestation_subnet_25/ssz_snappy
  - /eth2/82556a32/attestation_subnet_26/ssz_snappy
  - /eth2/82556a32/attestation_subnet_27/ssz_snappy
  - /eth2/82556a32/attestation_subnet_28/ssz_snappy
  - /eth2/82556a32/attestation_subnet_29/ssz_snappy
  - /eth2/82556a32/attestation_subnet_30/ssz_snappy
  - /eth2/82556a32/attestation_subnet_31/ssz_snappy
  - /eth2/82556a32/attestation_subnet_32/ssz_snappy
  - /eth2/82556a32/attestation_subnet_33/ssz_snappy
  - /eth2/82556a32/attestation_subnet_34/ssz_snappy
  - /eth2/82556a32/attestation_subnet_35/ssz_snappy
  - /eth2/82556a32/attestation_subnet_36/ssz_snappy
  - /eth2/82556a32/attestation_subnet_37/ssz_snappy
  - /eth2/82556a32/attestation_subnet_38/ssz_snappy
  - /eth2/82556a32/attestation_subnet_39/ssz_snappy
  - /eth2/82556a32/attestation_subnet_40/ssz_snappy
  - /eth2/82556a32/attestation_subnet_41/ssz_snappy
  - /eth2/82556a32/attestation_subnet_42/ssz_snappy
  - /eth2/82556a32/attestation_subnet_43/ssz_snappy
  - /eth2/82556a32/attestation_subnet_44/ssz_snappy
  - /eth2/82556a32/attestation_subnet_45/ssz_snappy
  - /eth2/82556a32/attestation_subnet_46/ssz_snappy
  - /eth2/82556a32/attestation_subnet_47/ssz_snappy
  - /eth2/82556a32/attestation_subnet_48/ssz_snappy
  - /eth2/82556a32/attestation_subnet_49/ssz_snappy
  - /eth2/82556a32/attestation_subnet_50/ssz_snappy
  - /eth2/82556a32/attestation_subnet_51/ssz_snappy
  - /eth2/82556a32/attestation_subnet_52/ssz_snappy
  - /eth2/82556a32/attestation_subnet_53/ssz_snappy
  - /eth2/82556a32/attestation_subnet_54/ssz_snappy
  - /eth2/82556a32/attestation_subnet_55/ssz_snappy
  - /eth2/82556a32/attestation_subnet_56/ssz_snappy
  - /eth2/82556a32/attestation_subnet_57/ssz_snappy
  - /eth2/82556a32/attestation_subnet_58/ssz_snappy
  - /eth2/82556a32/attestation_subnet_59/ssz_snappy
  - /eth2/82556a32/attestation_subnet_60/ssz_snappy
  - /eth2/82556a32/attestation_subnet_61/ssz_snappy
  - /eth2/82556a32/attestation_subnet_62/ssz_snappy
  - /eth2/82556a32/attestation_subnet_63/ssz_snappy
