log_level: debug
identity_libp2p_dir: /tmp/libp2p
identity_optp2p_dir: /tmp/mump2p
agent_lib_p2p_port: 33212
agent_opt_p2p_port: 43213
sidecar_listen_port: 33211
telemetry_enable: true
telemetry_port: 48123
enable_aggregation: true
gateway_cluster_id: optimum_hoodi_v0_3
gateway_id: local-dockerized
